### PR TITLE
Update to 4.x POM

### PR DESCRIPTION
**Pull request by jglick**
Just enough to let the plugin even be built by current versions of Java and Maven.

### CODE REVIEW

**Comment by Roemer** [comment]
Many many thanks for this!

**Comment by jglick** [comment]
To be clear, there are a lot of other updates that would be needed to bring this plugin in line with current metadata recommendations as in https://github.com/jenkinsci/archetypes; this was just the bare minimum to make it compatible with current tool versions.

**Comment by Roemer** [comment]
Yes, I think that is clear. I probably won't do that as I am now neither using Jenkins anymore (wish I could) and also not Docker Swarm anymore, so at least keeping it alive with the bare minimum is better than nothing.

**Comment by jglick** [comment]
Ah I see. Consider https://www.jenkins.io/doc/developer/plugin-governance/adopt-a-plugin/#how-can-i-mark-a-plugin-for-adoption

**Pull request merged**
