### PR TITLE
Fix apirequest jdk9+ compatibility

### PR DESCRIPTION
**Pull request by thorin**
Hi,

This PR fixes the following error which occurs on **okhttp3** when using a docker tcp connection with an **X.509 client certificate**, while running Jenkins with OpenJDK11:
```
[ERROR] [01/21/2020 09:20:25.055] [swarm-plugin-akka.actor.default-dispatcher-31] [akka://swarm-plugin/user/dead-agentService-reaper] clientBuilder.sslSocketFactory(SSLSocketFactory) not supported on JDK 9+
java.lang.UnsupportedOperationException: clientBuilder.sslSocketFactory(SSLSocketFactory) not supported on JDK 9+
        at okhttp3.internal.platform.Jdk9Platform.trustManager(Jdk9Platform.java:81)
        at okhttp3.internal.platform.Platform.buildCertificateChainCleaner(Platform.java:176)
        at okhttp3.OkHttpClient$Builder.sslSocketFactory(OkHttpClient.java:673)
        at org.jenkinsci.plugins.docker.swarm.docker.api.request.ApiRequest.<init>(ApiRequest.java:69)
        at org.jenkinsci.plugins.docker.swarm.docker.api.service.ListServicesRequest.<init>(ListServicesRequest.java:17)
        at org.jenkinsci.plugins.docker.swarm.docker.api.service.ListServicesRequest.<init>(ListServicesRequest.java:25)
        at org.jenkinsci.plugins.docker.swarm.DeadAgentServiceReaperActor.reapDeadAgentServices(DeadAgentServiceReaperActor.java:40)
        at org.jenkinsci.plugins.docker.swarm.DeadAgentServiceReaperActor.lambda$createReceive$0(DeadAgentServiceReaperActor.java:28)
        at akka.japi.pf.UnitCaseStatement.apply(CaseStatements.scala:24)
        at akka.japi.pf.UnitCaseStatement.apply(CaseStatements.scala:20)
        at scala.PartialFunction.applyOrElse(PartialFunction.scala:127)
        at scala.PartialFunction.applyOrElse$(PartialFunction.scala:126)
        at akka.japi.pf.UnitCaseStatement.applyOrElse(CaseStatements.scala:20)
        at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:175)
        at akka.actor.Actor.aroundReceive(Actor.scala:539)
        at akka.actor.Actor.aroundReceive$(Actor.scala:537)
        at akka.actor.AbstractActor.aroundReceive(AbstractActor.scala:227)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:612)
        at akka.actor.ActorCell.invoke(ActorCell.scala:581)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:268)
        at akka.dispatch.Mailbox.run(Mailbox.scala:229)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:241)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

### CODE REVIEW

**Comment by Roemer** [comment]
Do we need to add a switch to use the old code for JDK <9?

**Comment by thorin** [comment]
> Do we need to add a switch to use the old code for JDK <9?

Yes, you are correct. This doesn't work with JDK<9.
At the very least it needs a switch to use the old code.

**Comment by jswager-cisco** [comment]
We're encountering this problem on our Docker Swarms that are TLS protected. Is there an ETA when this fix will be released?

**Comment by Roemer** [comment]
Thank you for your contribution, it has been merged now.

**Pull request merged**
