### PR TITLE
fixed invalid characters in volume name

### LINKED ISSUE #33: Volume name of cache folder is invalid (due to » character)
We do use project folders in jenkins and are also using the plugin in a pipeline build. As a result, the whole path is used as the name of the docker volumes, e.g. "project_name»ci-build»branch" 
The error states, that there're invalid characters in the volume name (the » character of the folder structure is included in the name of the volume).

We've only tested it with cache folders, but there might be more places affected by this. 
This bug was encountered in 1.6,

### PR DESCRIPTION
**Pull request by vsfalexanderpilch**
fixes #33 by replacing invalid characters with 0. This is more restrictive than necessary, but it's easier to replace it this way (docker is allowing [a-zA-Z0-9][a-zA-Z0-9_.-]+). We're just allowing [a-zA-Z0-9]*.
The name of the volume is just used internally, so it doesn't have to look pretty.

### CODE REVIEW

**Comment by suryagaddipati** [comment]
hi @vsfalexanderpilch thank you for the PR. Do you think it would make sense to move that logic into ` computer.getVolumeName()` so its encapsulated better.

**Comment by vsfalexanderpilch** [comment]
I just figured out, that the last '-' character is important for the docker cache plugin:

> Volume name is expected to be in `<cache-name>-<unique-id>`

Docker won't run the service, if all '-' characters are replaced. As a result, there're now 2 strings to sanitize, so moving it to `computer.getVolumeName()` is just one half of the replacements.

**Comment by vsfalexanderpilch** [comment]
Docker swarm isn't able to launch the container, which might be related to https://github.com/suryagaddipati/docker-cache-volume-plugin/issues/2 

docker service ps:

`"starting container failed: error while mounting volume '': get part_of_project_0_ci_build_0_swarm_049-ild___swarm__49: no such volume"`

docker service inspect:

 "Mounts": [
                        {
                            "Type": "volume",
                            "Source": "part_of_project_0_ci_build_0_swarm_049-ild___swarm__49",
                            "Target": "/home/node/.m2",
                            "VolumeOptions": {
                                "DriverConfig": {
                                    "Name": "rapt/cachedriver"
                                }
                            }
                        }
                    ]

**Comment by Roemer** [comment]
So would this PR now be save to be merged? Are all problems you mentioned solved?

**Comment by vsfalexanderpilch** [comment]
I can't tell exactly, as the latest issue seemed to be related to the volume driver (rapt/cachedriver), which doesn't seem to be compatible with latest versions of docker. We stopped working on this as a result and didn't use the cache driver anymore. The driver doesn't seem to be maintained that actively, so I do have doubts that the usage is future-proof.

**Comment by Roemer** [comment]
This pr was auto-closed due to a master rebase. The new PR with this change is in #44

**Pull request closed without merging**
