### PR TITLE
Use a more unique agent name

### PR DESCRIPTION
**Pull request by smhc**
Using a timestamp can cause collisions with high degrees of parallelism. This was identified on https://github.com/jenkinsci/docker-swarm-plugin/issues/26

Using a counter rather than timestamp should resolve this issue.

### CODE REVIEW

**Comment by Roemer** [comment]
What will happen if the counter overflows? Would it still work and just start again?

**Comment by smhc** [comment]
It uses a modulus 9999999, so has a limit of 10 million before it wraps and starts again. 
If the counter itself wraps (after 2 billion builds) it will go negative and result in a double dash in the agent name, this shouldn't be an issue but may be nicer to have an abs() call there.

This is only the agent name and it gets deleted after the build is finished - It would be pretty unlikely to have more than 10 million of the same job running at the same time. So I am not sure the wrapping would cause a problem.

It is certainly better than the current implementation which is quite prone to collisions in matrix etc jobs which start many builds of the same name at roughly the same time.

**Comment by Roemer** [comment]
The atomic counter is global and not for each build a separate counter right? Could you add the `abs` there so we can prevent the double dashes?

**Comment by Roemer** [comment]
This pr was auto-closed due to a master rebase. The new PR with this change is in #45

**Pull request closed without merging**
