### PR TITLE
Support for TLS via docker commons plugin

### PR DESCRIPTION
**Pull request by smhc**
TLS support - Uses docker commons 'DockerServerEndPoint' with okhttp3 changes to support client certificates.

Support secrets & configs with files (i.e /run/secrets)

Support custom command to invoke slave agent by exposing jenkins agent secret and jnlp address via environment variables. Allows custom images that may already contain the slave to skip downloading it.

Some additional help and defaults in UI.

Fixes/enhancements to DockerSwarmAgentInfo log

### CODE REVIEW

**Comment by suryagaddipati** [comment]
hi @smhc . I will take a look at this week. Thank you for the PR.

**Comment by matthiasbaldi** [comment]
For me it works, thanks @smhc .

I get at the moment the following error while building a Maven application, but I think this is **for sure not an issue of this plugin**. In this error I loose the connection in every build execution after about 2min build time.

```
16:41:56 FATAL: command execution failed
16:41:56 java.io.IOException: Backing channel 'JNLP4-connect connection from vsrv01.xxxx.com/172.00.00.00:39686' is disconnected.
16:41:56 	at hudson.remoting.RemoteInvocationHandler.channelOrFail(RemoteInvocationHandler.java:209)
16:41:56 	at hudson.remoting.RemoteInvocationHandler.invoke(RemoteInvocationHandler.java:278)
16:41:56 	at com.sun.proxy.$Proxy84.isAlive(Unknown Source)
16:41:56 	at hudson.Launcher$RemoteLauncher$ProcImpl.isAlive(Launcher.java:1137)
16:41:56 	at hudson.Launcher$RemoteLauncher$ProcImpl.join(Launcher.java:1129)
16:41:56 	at hudson.Launcher$ProcStarter.join(Launcher.java:464)
16:41:56 	at org.jfrog.hudson.maven3.Maven3Builder.RunMaven(Maven3Builder.java:118)
16:41:56 	at org.jfrog.hudson.maven3.Maven3Builder.perform(Maven3Builder.java:113)
16:41:56 	at org.jfrog.hudson.pipeline.steps.ArtifactoryMavenBuild$Execution.run(ArtifactoryMavenBuild.java:108)
16:41:56 	at org.jfrog.hudson.pipeline.steps.ArtifactoryMavenBuild$Execution.run(ArtifactoryMavenBuild.java:61)
16:41:56 	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1$1.call(AbstractSynchronousNonBlockingStepExecution.java:47)
16:41:56 	at hudson.security.ACL.impersonate(ACL.java:290)
16:41:56 	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1.run(AbstractSynchronousNonBlockingStepExecution.java:44)
16:41:56 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
16:41:56 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
16:41:56 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
16:41:56 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
16:41:56 	at java.lang.Thread.run(Thread.java:748)
16:41:56 Caused by: java.nio.channels.ClosedChannelException
16:41:56 	at org.jenkinsci.remoting.protocol.NetworkLayer.onRecvClosed(NetworkLayer.java:154)
16:41:56 	at org.jenkinsci.remoting.protocol.impl.NIONetworkLayer.ready(NIONetworkLayer.java:142)
16:41:56 	at org.jenkinsci.remoting.protocol.IOHub$OnReady.run(IOHub.java:789)
16:41:56 	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)

```

**Comment by smhc** [comment]
Rebased and conflicts resolved. Can this PR be merged now? It'd be good to get it merged before any other changes introduce more conflicts - it contains many changes and fixes.

**Comment by suryagaddipati** [comment]
@smhc thank you for this. Looks  Great. Merged. I will make a release later today.

**Pull request merged**
