### PR TITLE
Allow passing credentials for private registries. #8

### PR DESCRIPTION
**Pull request by Crocmagnon**

### CODE REVIEW

**Comment by De1taE1even** [comment]
I'd love to see this merged.  It's a requirement for anyone running a private docker registry.

**Comment by Crocmagnon** [comment]
I have a branch with all my PR merged into one if you're interested. I can also provide a build but you'll have to install it manually in the plugin manager and you won't have updates but if you need the feature it may be better than nothing 😊

**Comment by Crocmagnon** [comment]
There you go : https://github.com/Crocmagnon/docker-swarm-plugin/releases/tag/docker-swarm-1.6-SNAPSHOT

**Comment by Crocmagnon** [comment]
Thank you @bpedersen2 for your review. You're right, I'll update this branch to use the credentials infrastructure.

**Comment by suryagaddipati** [comment]
@Crocmagnon would you be able to resolve the conflicts. I will get it merged asap.

**Comment by Crocmagnon** [comment]
Done

**Comment by Crocmagnon** [comment]
FYI I didn't make use of the credentials infrastructure, as per @bpedersen2 comment. Didn't have time for that, sorry.

**Comment by Crocmagnon** [comment]
?

**Comment by suryagaddipati** [comment]
@Crocmagnon do we still need this PR? If so, do you mind reopening it with conflicts resolved. I will merge and make a release asap. Thank you for your contributions.

**Comment by Roemer** [comment]
> FYI I didn't make use of the credentials infrastructure, as per @bpedersen2 comment. Didn't have time for that, sorry.

The default docker plugin now supports Jenkins credentials for Registries, maybe that can be copied?

**Pull request closed without merging**
