### PR TITLE
Credentials and custom DNS

### PR DESCRIPTION
**Pull request by Crocmagnon**
I integrated features from #12 and #13.

⚠️ I couldn't make any tests after merging the code from upstream ⚠️

### CODE REVIEW

**Comment by suryagaddipati** [comment]
Looks like build has compile errors?

**Comment by Crocmagnon** [comment]
Will check

**Comment by Crocmagnon** [comment]
Linux build is OK. Again, I was not able to run a functional test.

**Comment by Roemer** [comment]
What is the status of this PR?

**Comment by Crocmagnon** [comment]
Waiting for maintainer :)

**Comment by Roemer** [comment]
Can you maybe make two pull requests out of this?
One for the credentials and one for the rest?

**Comment by Crocmagnon** [comment]
@Roemer I'm sorry but I have no bandwidth to work on this at the moment and won't have for the next few months at least. Also, every progress I made in this direction seems to have been ignored by the maintainer. It does not help getting motivated.

Maybe @michaelPf85 could help but not sure.

**Comment by Roemer** [comment]
I created a PR based on your one just for the credential stuff. See #38 . It is also based on the latest master.

**Comment by Roemer** [comment]
As the credential stuff (with jenkins credentials) is now merged, would you be able to create a new PR just with the DNS stuff?

**Comment by Roemer** [comment]
This pr was auto-closed due to a master rebase. The credential stuff is already merged, the DNS stuff is now in #46

**Pull request closed without merging**
