### PR TITLE
Fixed invalid characters in volume name

### PR DESCRIPTION
**Pull request by Roemer**
This PR replaces #34 after the master rebase.

### CODE REVIEW

**Comment by Roemer** [comment]
@vsfalexanderpilch Do you mind having a quick look if this looks ok?

**Comment by hamza3202** [comment]
@Roemer any update on this?

**Comment by xeryany** [comment]
Hi! How can you currently use the plugin without this code? Normally all the builds use standard numbers (i.e. #23, #24) and any attempt to use the cached volumes feature would fail due to having invalid characters in the name. Thank you!

**Comment by opticabjohannsen** [comment]
Has anyone an idea, when this will be merged?
we'd love to use the feature with cached directories, which currently plain doesn't work

**Comment by Roemer** [comment]
This is now obsolete with the merge of #77.

**Pull request closed without merging**
